baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hiero'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Open Source'
url = '/#open-source'
weight = 20

[[menus.main]]
name = 'Contribute'
url = '/#contribute'
weight = 30

[[menus.main]]
name = 'Connect'
url = '/#connect'
weight = 40

[[menus.main]]
name = 'Roadmap'
url = '/#roadmap'
weight = 50